import { IFormFields } from "../types/IFormFields";

export const signupFormFields = [
  {
    id: "firstName",
    label: "First Name",
    type: "TEXT",
    mandatory: true,
    identifier: "firstName",
    editable: true,
    placeholder: "Type here",
    row: 1,
    column: 1,
  },
  {
    id: "lastName",
    label: "Last Name",
    type: "TEXT",
    mandatory: true,
    identifier: "lastName",
    editable: true,
    placeholder: "Type Here",
    row: 1,
    column: 2,
  },
  {
    id: "signUpKey",
    label: "Mobile Number or Email Address",
    type: "TEXT",
    mandatory: true,
    identifier: "signUpKey",
    editable: true,
    placeholder: "Enter mobile number or email here",
    row: 2,
    column: 1,
  },
  {
    id: "password",
    label: "Password",
    type: "TEXT",
    mandatory: true,
    identifier: "password",
    editable: true,
    placeholder: "Create password here",
    row: 3,
    column: 1,
  },
  {
    id: "confirmPassword",
    label: "Confirm Password",
    type: "TEXT",
    mandatory: true,
    identifier: "confirmPassword",
    editable: true,
    placeholder: "Re-enter password here",
    row: 4,
    column: 1,
  },
  {
    id: "referralCode",
    label: "Referral Code",
    type: "TEXT",
    mandatory: true,
    identifier: "referralCode",
    editable: true,
    placeholder: "Re-enter password here",
    row: 5,
    column: 1,
  },
];
